/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:b008cd90-14fe-472f-9cc4-9d5f170caf83",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_L6bUoFCcj",
    "aws_user_pools_web_client_id": "k3lvcle6dns0bh12bvgmlpda1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://h4ura2v3yfamtgo53qxjzx72ru.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jr2jmbzkgfbi3cyob5nzsgrloy",
    "aws_user_files_s3_bucket": "amplifyapp290f5229be0c84595bf022f673f8e1616122003-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
